baseURL               = "https://gptxgeek.com/"
languageCode          = "zh-CN"
title                 = "GPTXGeek"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"				# 站点静态文件保存目录


[params]
    author        = "yikai"
    description   = "GPTXGeek 网址导航 | AI tools"
    upload        = "https://github.com/martianyi/gptxgeek/discussions/2"      # 左侧导航栏的"网站提交"
    about         = ""	          # 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/martianyi/gptxgeek"  
    enablePreLoad = true					# 网站完全打开前预加载动画
    textPreLoad   = "GPTXGeek"				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = true					# 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			# 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"		# logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = true					# 默认站点为深色(夜间)模式
    yiyan         = true                         		# 默认启用一言服务
    fancybox      = true                                        # 使用 Fancybox 实现图片灯箱/放大功能

[params.seo]    
    baiduhmid       = ''	# 百度统计 hm.src 的 ID
    baiduSiteVer    = ''			# 百度HTML标签验证(baidu-site-verification)
    tj51laid        = ''                        		# 51.LA 网站统计
    tj51lack        = ''
    GoogleAdsClient = ''					# Google AdSense 

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.ico"
    searchImageL      = "assets/images/bg-dna.jpg"		# 搜索部分浅色背景图
    searchImageD      = "assets/images/bg-dna.jpg"		# 搜索部分深色背景图
    logoExpandLight   = "assets/images/logo-gptxgeek.webp"
    logoExpandDark    = "assets/images/logo-gptxgeek-dark.webp"
    logoCollapseLight = "assets/images/icon-gptxgeek.webp"
    logoCollapseDark  = "assets/images/icon-gptxgeek-dark.webp"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '&copy; {year} GPTXGeek By [Yi Kai](https://github.com/martianyi) <br/>'
